// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4S0UrHbK_FMtSqpDcgjpawChZAmZAxE',
    appId: '1:790071138550:web:85e56975c01f6337a2b4d7',
    messagingSenderId: '790071138550',
    projectId: 'instagram-69199',
    authDomain: 'instagram-69199.firebaseapp.com',
    storageBucket: 'instagram-69199.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtx4YxE3-u9vxm1RVBe38r8M5PBCZWo_I',
    appId: '1:790071138550:android:3e7c953e39b255e0a2b4d7',
    messagingSenderId: '790071138550',
    projectId: 'instagram-69199',
    storageBucket: 'instagram-69199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDQWy0Nkc37_HXcOZ4QWVJXNN4APtsXgw',
    appId: '1:790071138550:ios:2a95bd026e5bfbf6a2b4d7',
    messagingSenderId: '790071138550',
    projectId: 'instagram-69199',
    storageBucket: 'instagram-69199.appspot.com',
    iosBundleId: 'com.hanan.instagramFlutter',
  );
}
